default_platform(:ios)

platform :ios do

  desc "Generate App Store screenshots via fastlane snapshot"
  lane :screenshots do
    snapshot
  end

  desc "Generate screenshots and upload to App Store Connect"
  lane :screenshots_and_upload do
    snapshot
    deliver(
      skip_binary_upload: true,
      skip_metadata:      true,
      force:              true
    )
  end

end
